title: thefreebeginners
author: GitHub User
email: your-email@domain.com
description: > # a great way of learning 

# social links
twitter_username: szulfis
github_username:  szulfis

show_excerpts: true # it's a great way of learning

theme: jekyll-theme-architect
